example_1 <- list("GGCGTTCAGGCA", "AAGAATCAGTCA", "CAAGGAGTTCGC", "CACGTCAATCAC", "CAATAATATTCG")

example_2 <- list("GCCCAA", "GGCCTG", "AACCTA", "TTCCTT")

example_3 <- list("GAGGCGCACATCATTATCGATAACGATTCGCCGCATTGCC",
                  "TCATCGAATCCGATAACTGACACCTGCTCTGGCACCGCTC",
                  "TCGGCGGTATAGCCAGAAAGCGTAGTGCCAATAATTTCCT",
                  "GAGTCGTGGTGAAGTGTGGGTTATGGGGAAAGGCAGACTG",
                  "GACGGCAACTACGGTTACAACGCAGCAACCGAAGAATATT",
                  "TCTGTTGTTGCTAACACCGTTAAAGGCGGCGACGGCAACT",
                  "AAGCGGCCAACGTAGGCGCGGCTTGGCATCTCGGTGTGTG",
                  "AATTGAAAGGCGCATCTTACTCTTTTCGCTTTCAAAAAAA"
                  )

example_4 <- list("GCAGGTTAATACCGCGGATCAGCTGAGAAACCGGAATGTGCGT",
                  "CCTGCATGCCCGGTTTGAGGAACATCAGCGAAGAACTGTGCGT",
                  "GCGCCAGTAACCCGTGCCAGTCAGGTTAATGGCAGTAACATTT",
                  "AACCCGTGCCAGTCAGGTTAATGGCAGTAACATTTATGCCTTC",
                  "ATGCCTTCCGCGCCAATTGTTCGTATCGTCGCCACTTCGAGTG"
                  )

example_5 <- list("GACCTACGGTTACAACGCAGCAACCGAAGAATATTGGCAA",
                  "TCATTATCGATAACGATTCGCCGGAGGCCATTGCCGCACA",
                  "GGAGTCTGGTGAAGTGTGGGTTATGGGGCAGACTGGGAAA",
                  "GAATCCGATAACTGACACCTGCTCTGGCACCGCTCTCATC",
                  "AAGCGCGTAGGCGCGGCTTGGCATCTCGGTGTGTGGCCAA",
                  "AATTGAAAGGCGCATCTTACTCTTTTCGCTTAAAATCAAA",
                  "GGTATAGCCAGAAAGCGTAGTTAATTTCGGCTCCTGCCAA",
                  "TCTGTTGTTGCTAACACCGTTAAAGGCGGCGACGGCAACT"
                  )

real_data <- read.table("real_data_set.txt")
